[package]
name = "cf_minigrep"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Learning rust. Minigrep miniproject from the book."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
